const images = {
  common: {
    appIcon: require('./common/ic_app_icon.png'),
    eye: require('./common/ic_eye.png'),
    eyeClosed: require('./common/ic_eye_closed.png'),
    group: require('./common/ic_group.png'),
    bell: require('./common/ic_bell.png'),
    arrowRight: require('./common/ic_arrow_right.png'),
    add: require('./common/ic_add.png'),
    filter: require('./common/ic_filter.png'),
    search: require('./common/ic_search.png'),
    list: require('./common/ic_list.png'),
    chevronForward: require('./common/ic_chevron_forward.png'),
    close: require('./common/ic_close.png'),
    closeRounded: require('./common/ic_close_round.png'),
    addRing: require('./common/ic_add_ring.png'),
    check: require('./common/ic_check.png'),
    expandRight: require('./common/ic_expand_right_double.png'),
    calendarFilled: require('./common/ic_calendar_filled.png'),
    homeAlt: require('./common/ic_home_alt.png'),
    imgMapMarker: require('./common/img_map_marker.png'),
    imgBell: require('./common/img_bell.png'),
    location: require('./common/ic_location.png'),
    barcode: require('./common/ic_barcode.png'),
    chevronLeft: require('./common/ic_chevron_left.png'),
    chevronRight: require('./common/ic_chevron_right.png'),
    emptyBox: require('./common/ic_empty_box.png'),
    syncOutline: require('./common/ic_sync_outline.png'),
    flash: require('./common/ic_flash.png'),
    ticketStar: require('./common/ic_ticket_star.png'),
    boxes: require('./common/ic_boxes.png'),
    timeFill: require('./common/ic_time_fill.png'),
    timeProgress: require('./common/ic_time_progress.png'),
    timeProgressDuotone: require('./common/ic_time_progress_duotone.png'),
    userCircle: require('./common/ic_user_circle.png'),
    caretDown: require('./common/ic_caret_down.png'),
    squareUncheck: require('./common/ic_square_uncheck.png'),
    squareCheck: require('./common/ic_square_checked.png'),
  },
  auth: {
    account: require('./auth/ic_account.png'),
    phone: require('./auth/ic_phone.png'),
    password: require('./auth/ic_password.png'),
  },
  tab: {
    home: require('./tab/ic_home.png'),
    clients: require('./tab/ic_customers.png'),
    createOrder: require('./tab/ic_create_order.png'),
    orders: require('./tab/ic_orders.png'),
    others: require('./tab/ic_others.png'),
  },
  navigation: {
    back: require('./navigation/ic_back.png'),
  },
  home: {
    background: require('./home/ic_background.png'),
    navigate: require('./home/ic_navigate.png'),
    bag: require('./home/ic_bag.png'),
    male: require('./home/ic_male.png'),
    map: require('./home/ic_map.png'),
    loupe: require('./home/ic_loupe.png'),
    fingerprint: require('./home/ic_fingerprint.png'),
    fire: require('./home/ic_fire_fill.png'),
    promotion: require('./home/ic_promotion.png'),
    router: require('./home/ic_router.png'),
  },
  profile: {
    map: require('./profile/ic_map.png'),
    pointers: require('./profile/ic_pointers.png'),
    password: require('./profile/ic_password.png'),
    dateRange: require('./profile/ic_date_range_fill.png'),
    timeProgress: require('./profile/ic_time_progress_fill.png'),
  },
  client: {
    call: require('./client/ic_call.png'),
    calendar: require('./client/ic_calendar.png'),
    location: require('./client/ic_location.png'),
    user: require('./client/ic_user.png'),
    login: require('./client/ic_login.png'),
    logout: require('./client/ic_logout.png'),
    index: require('./client/ic_index.png'),
    notification: require('./client/ic_notification.png'),
    edit: require('./client/ic_edit.png'),
    verified: require('./client/ic_verified.png'),
    ban: require('./client/ic_ban.png'),
    cube: require('./client/ic_cube.png'),
    receipt: require('./client/ic_receipt.png'),
    pointers: require('./client/ic_pointers.png'),
    documentText: require('./client/ic_document_text.png'),
    gps: require('./client/ic_gps_fixed.png'),
    store: require('./client/ic_store.png'),
    transfer: require('./client/ic_transfer.png'),
    ribbon: require('./client/ic_ribbon.png'),
    storeMarker: require('./client/ic_store_marker.png'),
    buffer: require('./client/ic_buffer.png'),
    fileDockAdd: require('./client/ic_file_dock_add.png'),
    barcode: require('./client/ic_barcode.png'),
    boxes: require('./client/ic_boxes.png'),
    coin: require('./client/ic_coin.png'),
    personEdit: require('./client/ic_person_edit.png'),
    tag: require('./client/ic_tag.png'),
    infoCircle: require('./client/ic_info_circle.png'),
    cubeSolid: require('./client/ic_3d_cube_solid.png'),
    cartSolid: require('./client/ic_cart_solid.png'),
    contactCardSolid: require('./client/ic_contact_card_solid.png'),
    contactPhoneBookSolid: require('./client/ic_contact_phonebook_solid.png'),
    fileUserSolid: require('./client/ic_file_user_solid.png'),
    shipping: require('./client/ic_shipping.png'),
    wallet: require('./client/ic_wallet.png'),
  },
  staff: {
    map: require('./staff/ic_map.png'),
  },
  route: {
    mapOutlined: require('./route/ic_map_outlined.png'),
    pinAlt: require('./route/ic_pin_alt_fill.png'),
    checkInOutlined: require('./route/ic_check_in_outlined.png'),
    checkOutOutlined: require('./route/ic_check_out_outlined.png'),
    storeRed: require('./route/ic_5g_store_red.png'),
    storeYellow: require('./route/ic_5g_store_yellow.png'),
  },
  othersTab: {
    wayToPinLocation: require('./others-tab/ic_way_to_pin_location.png'),
    reverseClock: require('./others-tab/ic_reverse_clock.png'),
    cubeWithLoupe: require('./others-tab/ic_cube_with_loupe.png'),
    pinUser: require('./others-tab/ic_pin_user.png'),
    promotion: require('./others-tab/ic_promotion.png'),
    turbine: require('./others-tab/ic_turbine.png'),
    roadFinish: require('./others-tab/ic_road_finish.png'),
    pieChartFill: require('./others-tab/ic_pie_chart_fill.png'),
    signOut: require('./others-tab/ic_sign_out.png'),
  },
  returnProduct: {
    warehouse: require('./return_product/warehouse.png'),
    edit: require('./return_product/edit.png'),
  },
};

export default images;
