import { PosOrderState } from '@app/enums/pos-order-state.enum';
import { ErpBaseEntity } from './erp-base.entity';
import { PosOrderLine } from './pos-order-line.entity';
import { PromotionProgram } from './promotion-program.entity';
import { ShippingAddressType } from '@app/enums/shipping-address-type.enum';
import { JournalType } from '@app/enums/journal-type.enum';

export interface PosOrder extends ErpBaseEntity {
  partner_id?: [number, string];
  partner_code?: string;
  receiver_name?: string;
  delivery_address_id?: [number, string];
  phone?: string;
  partner_address_details?: string;
  country_type_id?: [number, string];
  town_id?: [number, string];
  district_id?: [number, string];
  state_id: [number, string];
  delivery_expected_date?: string;
  shipping_address_type: ShippingAddressType;
  distributor_id: [number, string];
  sales_company_code: string;
  user_id: [number, string];
  team_id: [number, string];
  sup_id: [number, string];
  asm_id: [number, string];
  rsm_id: [number, string];
  crmf99_system_id: [number, string];
  ctkm_id: PromotionProgram;
  crm_group_id: [number, string];
  salesperson_note?: string;
  pricelist_id: [number, string];
  currency_id: [number, string];
  currency_rate: number;
  journal_name: JournalType;
  sale_date: string;
  state: PosOrderState;
  create_date: string;
  tongtruocchietkhau: number;
  chietkhautongdon: number;
  amount_untaxed: number;
  amount_tax: number;
  amount_total: number;
  checkin_out_id: boolean;
  detail_plan_id: boolean;
  router_plan_id: boolean;
  order_line: PosOrderLine[];
  phantramchietkhautongdon?: number;
}
